name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest

             - name: Check Docker Hub secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME1 }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN1 }}
        run: |
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "DOCKERHUB_USERNAME1 is EMPTY or NOT AVAILABLE"
          else
            echo "DOCKERHUB_USERNAME1 is available"
          fi

          if [ -z "$DOCKER_TOKEN" ]; then
            echo "DOCKERHUB_TOKEN1 is EMPTY or NOT AVAILABLE"
          else
            echo "DOCKERHUB_TOKEN1 is available"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME1 }}
          password: ${{ secrets.DOCKERHUB_TOKEN1 }}

      - name: Build Docker image
        run: |
          docker build -t ajay0706/cicd-flask-demo:latest .

      - name: Push Docker image
        run: |
          docker push ajay0706/cicd-flask-demo:latest
